/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  sidebar: [
    {
      type: 'category',
      label: 'Installing',
      items: [
        'installation-requirements',
        {
          type: 'category',
          label: 'Installing the Admin Console',
          items: [
            'installation-admin-console',
            'installation-existing-cluster',
            'installation-vm',
            'installation-air-gap',
          ],
        },
        'app-configuration'
      ],
    },
    {
      type: 'category',
      label: 'Upgrading',
      items: [
        'upgrade-app',
        'upgrade-kots',
        'upgrade-kurl',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        'troubleshooting',
        'support-bundle-create-ui',
        'uninstall-admin-console',
        'uninstall-app',
      ],
    },
    {
      type: 'category',
      label: 'kots CLI',
      items: [
        'kots-cli-install',
      ],
    },
  ],
};

module.exports = sidebars;
